beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanBuilderFactory.java

Ensure that the traceId that passed sampling gets passed in to the sampling span.

Ensure same traceId is used for sampling and downstream generated spans.

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/Beeline.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientRequestAdapter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientResponseAdapter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerRequestAdapter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerRequestSpanCustomizer.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerResponseAdapter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/utils/TraceFieldConstants.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagatorTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagatorTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpServerRequestCustomizerTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/MockSpanUtils.java
beeline-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
beeline-spring-boot-starter/pom.xml
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/BeelineRestTemplateInterceptor.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/BeelineServletFilter.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/utils/InstrumentationConstants.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/utils/MoreTraceFieldConstants.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/mockmvctests/MockMvcTest.java
pom.xml

- Added high-level utilities to make manual instrumentation of HTTP client/server easier.
- Refactored the Spring starter's ServletFilter and RestTemplate Interceptor to use these.
- Deprecated constants in the Spring starter and moved them to Core where appropriate.
- Configured Mockito to allow mocks on final classes.
- Fixed a versioning issue in the parent POM: the POM was referencing an old version of Core.
Below are some points that are worth pointing out:
1. AFAIK, when we were creating the Spring HTTP instrumentation, Honeycomb said that the span names generated by this should be low cardinality. As such, the span name generated by the [BeelineRestTemplateInterceptor](https://github.com/wtce/beeline-java/blob/http-trace-propagation-utilities/beeline-spring-boot-starter/src/main/jav …

http-propagation-utilities (honey-7):

---

beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/CautiousResponseObserver.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/DebugResponseObserver.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfigTest.java
beeline-spring-boot-starter/src/test/resources/application-path-pattern-test.properties
beeline-spring-boot-starter/src/test/resources/application-request-test.properties

Changes:
- debug response observer is added unless explicitly disabled. Test using configuration tests.
- test profiles disable the observer as existing test configuration means that the mocks are invoked at Spring configuration time if observer is present.
- add a version of the reponse observer which logs 401s at ERROR level. This is not used by default, but is available to library users if they want to configure it.
@asdvalenzuela 
Note that this changes the default behaviour of the Beeline; prior to this, if you ran it with the default settings and got your write key incorrect, you would see ERROR logs; this is because there would be no response observer registered and so Libhoney would log at ERROR level when a 401 occurred. Now you won't see anything unless you switch the logs to …

debug-response-observer (honey-3):

---

beeline-core/src/main/java/io/honeycomb/beeline/DefaultBeeline.java

Resolves #19: The call to `tracer.endTrace()` within `DefaultBeeline.close()` was misleading because it will only end the trace local to the thread that called `DefaultBeeline.close()`, instead of closing all traces.

remove endTrace from DefaultBeeline.close() method as it is misleading

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/SendingSpan.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Span.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Tracer.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/TracerSpan.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Tracing.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/context/ThreadLocalTracingContext.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/context/TracingContext.java

This allows us to be more flexible in how we track related spans, especially for systems that
use fixed-size thread pools that recycle threads (which can cause problems with ThreadLocals
because they can inherit incorrect contexts, etc).
Also, making some small adjustments to Span.toString() to allow it to report on actual
class / sub-class in use.

Add TracingContext interface to enable other ways to hold spans for a request

---

pom.xml

Apparently the old one had a vulnerability alerted by a customer's scanner

Bump wiremock version

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanBuilderFactory.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Tracing.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/TraceIdProvider.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/UUIDTraceIdProvider.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/W3CTraceIdProvider.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/SpanBuilderFactoryTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/TracerTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/TracingTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/ids/UUIDTraceIdProviderTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/ids/W3CTRaceIdProviderTest.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/e2e/End2EndTest.java

Adds support for W3C Trace (16 byte) and Span (8 byte) IDs.
This changed has the following parts:
- extend TraceIdProvider to create separete Trace and Span IDs
- implement new functions in UUIDTraceIdProvider that return UnsupportedOperationException
- add W3CTraceIdProvider and tests
- update direct usage of UUIDTraceIdProvider to W3CTraceIdProvider in SpanBuilderFactory and tests

Add support for W3C Trace and Span ID generation

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/utils/TraceFieldConstants.java
beeline-spring-boot-starter/pom.xml
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/BeelineQueryListenerForJDBC.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/DataSourceProxyBeanPostProcessor.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfigTest.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/beans/BeelineQueryListenerForJDBCTest.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/beans/DataSourceProxyBeanPostProcessorTest.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/mockmvctests/MockMvcTest.java

This automatically proxies DataSource and adds query listener to Spring. This will use the Beeline to send JDBC traces to Honeycomb.
To disable this behavior, set `honeycomb.beeline.jdbc.enabled=false` in Spring's application properties.

Added BeelineQueryListenerForJDBC to auto-instrument JDBC

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/W3CTraceIdProvider.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/Propagation.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodecTest.java

This change adds a W3C spec compatible PropagationCodec that is built on top of the W3C `traceparent` http header. This propagation codec does not support additional trace context provided by the `tracecontext` http header.
This change also extends the W3CTraceIdProvider to provide access methods for validating trace and span IDs.
~~__NOTE__: This PR is based on #50 and I'll leave this PR as draft until it has been merged. Please view [01df9345](https://github.com/honeycombio/beeline-java/commit/01df93452d0f57a67a1413c584b5a475083027ab) directly for just the changes for adding the W3C propagation codec.~~
#50 has now been merged.

Add support for W3C http header propagation

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/AWSPropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/BeelineServletFilter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientRequestAdapter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpRequestAdapter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerRequestAdapter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/Propagation.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/AWSPropagationCodecTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/BeelineServletFilterTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagatorTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodecTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagatorTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodecTest.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/BeelineRestTemplateInterceptor.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/mockmvctests/MockMvcTest.java

This change refactors implementations of `PropagationCodec` (HoneyCombV1, W3C & AWS) to use a `Map<String, String>` instead of a single string value. This is so that we can read / write across multiple headers (eg traceparent & tracestate).
This also has the side effect of reducing the reliance of a particular codec's header being used directly and instead relies on the codec to finding / creating the headers it cares about.
~~**NOTE:** Creating this as draft while I have a couple of mocked tests to fix up in HttpServerPropagatorTest.~~
~~- [x] whenStartPropagation_traceIsStarted_andHttpFieldsAreApplied~~
~~- [x] whenStartPropagation_andNoTraceHeaderIsPresent_traceIsStarted_andHttpFieldsAreApplied~~
The PR consists of the following parts:
- Updating each `PropagationCodec` implementation …

Refactor propagator codec implementations to use map<string, string> for encode & decode

---

beeline-core/src/test/java/io/honeycomb/beeline/tracing/sampling/DeterministicSamplerTest.java

Junit deterministic sampler can be a little temperamental and not yield consistent results. This refactor uses a simpler approach by using a double as the acceptable tolerance percentage and working out the upper and lower bounds.

Refactor deterministic sampler test to not use junit closeTo comparison

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodec.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineProperties.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfigTest.java

Switch to use abbreviated codec name.

Use 'hny' for honeycomb propagation codec name

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/W3CTraceIdProvider.java

[SecureRandom](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html) is a cryptographic random number generator and may offer a better spread compared to the standard pseudo Random generator.

Use secure random in W3C trace ID generator

---

beeline-spring-boot-starter/src/main/resources/META-INF/spring-configuration-metadata.json

Fixes #55 (@kvrhdn).
Adds metadata to describe config properties used in both `BeelineProperties` and `BeelineAutoconfig`.

Add config metadata for beeline properties

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/BeelineServletFilter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagator.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagatorTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagatorTest.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/BeelineRestTemplateInterceptor.java

Adds `HttpClientPropgator.tracePropagationHook` and `HttpServerPropagator.traceParserHook` to provide custom functions consumers of the beeline can use to manage trace context on incoming / outgoing HTTP requests.
Also includes a builder classes to make it easier configure the HttpClientPropagator & HttpServerPropagator with optional parameters.
Example of setting up a propagation hook to set HTTP headers using the W3C format on outgoing requests:
```java
final HttpClientPropagator propagator = new HttpClientPropagator.Builder(tracer, r -> "span-name")
.setTracePropagationHook((request, context) -> {
return Propagation.w3c().encode(mockContext);
})
.build();
```
Example of setting a parser hook to extract a propagation context from an incoming HTTP request that first tries the W3C then …

Add parse and propagation hooks

---

pom.xml

Bump `maven-javadoc-plugin` version to latest (v3.2.0).
We were seeing some unusual errors on the previous version (v3.0.0) related to NullPointerExceptions when trying to package the projects. This was resolved in [MJAVADOC-517](https://issues.apache.org/jira/browse/MJAVADOC-517) that was part of release v3.0.1.

Bump maven-javadoc-plugin to v3.2.0

---

beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineProperties.java
beeline-spring-boot-starter/src/main/resources/META-INF/spring-configuration-metadata.json
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfigTest.java

Adds support for configuring a proxy via SpringBoot's AutoConf settings. The username and password can be optionally set if required.
Use proxy without username / password:
```
honeycomb.beeline.proxyHostname=http://localhost:1234
```
Use proxy with username & password:
```
honeycomb.beeline.proxyHostname=http://localhost:1234
honeycomb.beeline.proxyUsername=username
honeycomb.beeline.proxyPassword=password
```

Add support for configuring a proxy via spring boot AutoConf settings

---

CHANGELOG.md
beeline-core/pom.xml
beeline-core/src/test/java/io/honeycomb/beeline/builder/BeelineBuilderTest.java
beeline-spring-boot-sleuth-starter/pom.xml
beeline-spring-boot-starter/pom.xml
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
pom.xml

Prepares the next release of the Beeline, including Spring Boot and Slueth.
Included changes:
- update beeline version to 1.4.0
- update libhoney dependency to 1.3.0
- fixes a negative verification test as part of the libhoney update in BeelineBuilderTest
NOTE: Depends on pending [libhoney 1.3.0](https://github.com/honeycombio/libhoney-java/pull/36) release.

Prepare v1.4.0 release

---

beeline-spring-boot-sleuth-starter/pom.xml
beeline-spring-boot-starter/pom.xml
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java

Libhoney's HoneyClientBuilder was extended to offer an overload of apiHost that takes a pre-built URI. This is useful because we already have a pre-built URI as part of the autoconf beelineproperties and means we don't have to cast back to a string.
NOTE: This change includes updating both the spring boot and sleuth projects to use the latest beeline 1.4.0 version.

Use HoneyClientBuilder.apiHost URI overload 

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodecTest.java

Adds support for encoding & decoding dataset and other trace fields in W3C's `tracestate` header.
NOTE: It does not limit the vendor opaque value to 256 characters as per the W3C spec.

Add tracestate parsing / propagation to W3C codec

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/Span.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/TracerSpan.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/SendingSpanTest.java
beeline-spring-boot-sleuth-starter/src/main/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporter.java
beeline-spring-boot-sleuth-starter/src/test/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporterTest.java

Normally a span's elapsed duration is calculated using the JVM monotonic start time. However, when converting a span from another format (eg Zipking using the BraveBeelineReporter) that provides it's own start times, it's not possible to accurately use the monotonic clock and makes the duration widely inaccurate.
This change allows a span to explicitly set it's duration that be used in place of the traditional calculation. The default behaviour is to rely on the monotonic clock.

Allow span duration to be set directly

---

.circleci/config.yml

- Move to use the maven orb provided by circle ci
- Use build matrix to simplify the config file
- Add the appropriate filters to the publish jobs so that they run when a build is tagged
If this looks good it should be easily able to be ported over to https://github.com/honeycombio/libhoney-java

Rework build, add matrix and use orb, fix tag filters

---

.circleci/config.yml

Created as part of https://github.com/honeycombio/libhoney-java/pull/41 so that we can share the maven creds between the repos

Use new context for maven creds

---

.circleci/config.yml
beeline-core/src/main/java/io/honeycomb/beeline/DefaultBeeline.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Beeline.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/SendingSpan.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Span.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanBuilderFactory.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanPostProcessor.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Tracer.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/TracerSpan.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/TraceIdProvider.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/UUIDTraceIdProvider.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/W3CTraceIdProvider.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/AWSPropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/CompositeHttpHeaderPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/PropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/PropagationContext.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/sampling/DeterministicTraceSampler.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/sampling/TraceSampler.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineMetaFieldProvider.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/beans/aspects/ChildSpan.java

While preparing the v1.15.0 release (#92), two issues were found that prevented it from successfully building on Circle CI:
1) The updated circle CI config used a new circle CI provided orb to do the pom.xml caching for us, unfortuently the command also executed a dependency check with a go-offline flag, which meant it needs to be able to resolve all dependencies from public sources; in our project the spring boot and sleuth packages depend on beeline-core, and as we were updating the beeline-core module too, it couldn't resolve it. This has been fixed by doing the caching ourselves and doing the dependency check as part of the testing.
2) We're now testing for Java 13, which has stricter javadoc rules and do not allow h1 tags in class & property comments. I've had to switch these over to …

Fix CircleCI test failures

---

beeline-spring-boot-sleuth-starter/src/main/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporter.java
beeline-spring-boot-sleuth-starter/src/test/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporterTest.java

PR #87 submitted by @tyler-boyd had some failing tests.
This PR supersedes Tyler's PR by providing the same commit to update the BraveBeelineReporter to correctly use the span's parent ID to create the propagation context and fixes the broken tests.

Change Brave span transforming to properly associate spans

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodecTest.java

Receiving OTEL instrumentation ignores spans coming with the `00` sampled flag.
This is a stop-gap measure to ensure w3c parser hooks work with an OTEL receiver. Ideally, we would like to set the sampled flag based on an actual sampler, but that requires further investigation.

Default w3c sampled flag to 01

---

.github/dependabot.yml
.github/workflows/apply-labels.yml

Also tell dependabot to label PRs as maintenance.

add our custom action to manage project labels

---

CONTRIBUTORS
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Tracer.java

Adds the name of the most nested open span when ending trace with active child spans.
Trying to work out which span has incorrectly not been closed can be a PITA. So let's make it a little easier by logging the most nested child span's name.
This is a small _logging only_ change, with no obvious way of unit testing unless we inject the logger.  Let me know if you're happy for this to not have a unit test.  All existing tests pass.

Improve end trace logging

---

.circleci/maven-release-settings.xml

- fixes #157 
- release plugins in the parent pom.xml were configured for the `release` profile, but we were setting active profile to `gpg` in the release-settings.xml
- verified locally by publishing the 1.6.1 artifacts

ci: fix maven release

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/BeelineServletFilter.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/DefaultPropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpClientPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderPropagationCodecFactory.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpServerPropagator.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/Propagation.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/BeelineServletFilterTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderPropagationCodecFactoryTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/PropagationTest.java

- closes #165 
- Adds default codec to parse either Honeycomb (if specified) or W3C trace propagation header. If both are present, Honeycomb header will be parsed.

feat: parse both w3c and honeycomb propagation headers by default

---

CHANGELOG.md
RELEASING.md
beeline-core/pom.xml
beeline-spring-boot-sleuth-starter/pom.xml
beeline-spring-boot-starter/pom.xml
pom.xml

- Version bump and changelog update.
- Update to RELEASING to update the `beelineVersion` tag in springy POMs, too.

Prepare v1.7.0

---

RELEASING.md
beeline-spring-boot-sleuth-starter/pom.xml
beeline-spring-boot-starter/pom.xml

Publishing the spring-boot artifacts fails if these reference a version that isn't already published. A future todo: [resolve publishing these versions together](https://github.com/honeycombio/beeline-java/issues/173).
This merge commit will get retagged as the v1.7.0 release.

dial version back to one already published

---

RELEASING.md

- As referenced in issue #173 the beeline cannot be published with submodules depending on the same version. This note/change in release process helps ensure the beeline publish process is successful until that issue is resolved.
- Add temporary note into `RELEASING.md` to _not_ update `beelineVersion` until the issue is resolved (getting a newer maven dependency plugin in the orb and subsequently upgrading the orb version in circleci config)

maint: update releasing.md for current temporary issue

---

.circleci/config.yml

- closes #173 
- upgrade maven orb in circle config, which includes newer `maven-dependency-plugin:3.1.2` instead of the default 2.8. This plugin includes a [fix for resolving artifacts](https://issues.apache.org/jira/browse/MDEP-204) that should be available as intermodule dependencies.

maint: update maven orb to handle multi-module project

---

beeline-core/src/main/java/io/honeycomb/beeline/DefaultBeeline.java
beeline-core/src/main/java/io/honeycomb/beeline/builder/BeelineBuilder.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Beeline.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Tracing.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java
beeline-core/src/test/java/io/honeycomb/beeline/builder/BeelineBuilderTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodecTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodecTest.java

Adds E&S support by moving service name to be a beeline property updating BeelineBuilder to determine environment type from API key and use default values as appropriate.
The beeline also now assigns a default service name based on the API key provided. Classic gets "beeline-go" and non-classic gets "unknown_service:{process-name}" where process name is the exe/jar name and falls back to "java" is it cannot resolve it.
The Beeline now applies the following defaults:
| Property | Classic | Non-classic |
| - | - | - |
| service name | unknown_service:java | unknown_service:java |
| dataset | beeline-java | unknown_service |
We no longer propagate dataset in the Honeycomb or W3C propagation codecs. This is because each app should set it's own service name, and no infer the dataset from an …

Add support for Environment & Services

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanPostProcessor.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/utils/TraceFieldConstants.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/SendingSpanTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/SpanPostProcessorTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/TracerTest.java

- We decided we would start adding `service.name` field for more consistency with OpenTelemetry. `service_name` continues to be sent.
- add `service.name` field in addition to `service_name`

feat: add service.name field in addition to service_name

---

CONTRIBUTORS
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineConfig.java

* Fixes the [Issue #180](https://github.com/honeycombio/beeline-java/issues/180). Application fails to start because of circular dependencies in Spring 2.6.x and above.
Split autoconfiguration and generic bean configuraiton classes. This way `BeelineAutoconfig` can autowire `BeelineHandlerInterceptor` declared in either `BeelineConfig` or somewhere else. Existing tests already cover the change.

fix circular dependency for spring boot 2.6.x

---

CONTRIBUTORS
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfig.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineConfig.java

Split autoconfiguration and generic bean configuraiton classes. This way BeelineAutoconfig can autowire BeelineHandlerInterceptor declared in either BeelineConfig or somewhere else. Existing tests already cover the change.
- we created the `releases-1.x.x` branch to patch the 1.x.x line since we already have breaking changes on `main` that will be released as `2.0.0`
- this cherry-picks the fix for spring boot 1.6 circular dependency from `main`

fix circular dependency for spring boot 2.6.x (#190)

---

beeline-core/src/main/java/io/honeycomb/beeline/builder/BeelineBuilder.java
beeline-core/src/test/java/io/honeycomb/beeline/builder/BeelineBuilderTest.java

- Previous prep for E&S trimmed service name, but we don't want to mutate service name - we should only trim for the purposes of setting the dataset, and otherwise leave service name as-is.
- don't trim service name
- trim dataset derived from service name, set to unknown_service as needed
- warn on diff if space is in service name that doesn't translate into the dataset
- update tests to confirm non-trimming of service name, and proper setting of default dataset

fix: only trim service name for dataset

---

CHANGELOG.md
RELEASING.md
beeline-core/pom.xml
beeline-spring-boot-sleuth-starter/pom.xml
beeline-spring-boot-starter/pom.xml
pom.xml

- breaking release because dataset propagation was removed in #187 
- also removing the releasing docs version weirdness since we saw it work when we released 1.7.1

prepare 2.0.0 release

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/Beeline.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/SendingSpan.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/Span.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/SpanBuilderFactory.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/SendingSpanTest.java
beeline-core/src/test/java/io/honeycomb/beeline/tracing/SpanBuilderFactoryTest.java

Adds support for recording whether a span is a root or subroot span within the trace. Root means it is the very first span across all services and subroot means it is the first span within a given service.
When starting a new trace manually, via instrumentation or via propagation, `StartTrace` is used so this will ensure that meta.span_type is correctly set.
- Closes #202
- Adds setRoot and isRoot to Span
- Add setRoot to SpanBuilder
- During SendingSpan.Close, check for isRoot and add `meta.span_type` if set
- Add tests for SendingSpan and SpanBuilder

Add meta.span_type to root/subroot spans

---

.circleci/config.yml

update default version to 17
- Java 18 was released in March 😄 
- add to test matrix
- use a more recent version (17) by default

maint: add Java 18 to CI matrix

---

beeline-core/src/main/java/io/honeycomb/beeline/builder/BeelineBuilder.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/ids/W3CTraceIdProvider.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/AWSPropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderPropagationCodecFactory.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/HttpHeaderV1PropagationCodec.java
beeline-core/src/main/java/io/honeycomb/beeline/tracing/propagation/W3CPropagationCodec.java

Fixes javadoc warnings for incorrect param name, spelling error or import path.
- Fix javadoc warnings

Fix javadoc warnings

---

beeline-core/src/test/java/io/honeycomb/beeline/tracing/sampling/DeterministicSamplerTest.java
beeline-spring-boot-sleuth-starter/pom.xml
beeline-spring-boot-sleuth-starter/src/test/java/io/honeycomb/beeline/spring/beans/BraveBeelineReporterTest.java
beeline-spring-boot-starter/pom.xml
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/mockmvctests/MockMvcTest.java
examples/pom.xml
pom.xml

Both the Spring Boot and Sleuth packages need to reference the beeline-core package. These are set as hardcoded values so do not automatically get updated.
This PR creates a new property in the root POM that uses the current beeline project version and this is then used by those packages to keep them inline.
To support moving to beeline v2+ in the spring boot and sleuth packages, a couple of tweaks were needed to accommodate dataset not being populated as part of context propagation.
Also fixes a bug in the examples POM where it uses a hard coded libhoney version instead of the room POMs libhoneyVersion property.
- Create beelineVersion property in root POM
- Use new property in both spring boot and sleuth packages
- Updated spring boot test that asserted dataset was not propagated and …

Fix project versions and use latest in Spring Boot / Sleuth packages

---

.github/dependabot.yml

- we can't upgrade to [mockito 5](https://github.com/mockito/mockito/releases/tag/v5.0.0) because they dropped support for java 8

maint: ignore mockito 5 updates

---

.github/dependabot.yml

- Spring Boot 3.x.x comes with breaking changes #278

maint: ignore spring boot 3 upgrade

---

beeline-core/src/main/java/io/honeycomb/beeline/builder/BeelineBuilder.java
beeline-core/src/test/java/io/honeycomb/beeline/builder/BeelineBuilderTest.java
pom.xml

We [recently](https://github.com/honeycombio/libhoney-java/releases/tag/v1.6.0) updated libhoney-java to support classic ingest keys. This PR updates the beeline to this version of libhoney-java and swaps isClassic to use the new static method from libhoney.
- bumps libhoney-java version from 1.5.4 to 1.6.0
- removes `BeelineBuilder.isClassic` in favor of `libhoney.Options.isClassic`
- Adds several tests that use classic/non-classic ingest keys to verify it works

feat: support classic ingest keys

---

beeline-core/src/main/java/io/honeycomb/beeline/tracing/Beeline.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineConfig.java
beeline-spring-boot-starter/src/main/java/io/honeycomb/beeline/spring/autoconfig/BeelineProperties.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/autoconfig/BeelineAutoconfigTest.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/mockmvctests/MockMvcTest.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/mockmvctests/MockMvcTestClassic.java
beeline-spring-boot-starter/src/test/java/io/honeycomb/beeline/spring/mockmvctests/MockMvcTestIngest.java
beeline-spring-boot-starter/src/test/resources/application-path-pattern-test.properties
beeline-spring-boot-starter/src/test/resources/application-request-test-classic.properties
beeline-spring-boot-starter/src/test/resources/application-request-test-ingest.properties
beeline-spring-boot-starter/src/test/resources/application-request-test.properties
example-spring/README.md
example-spring/pom.xml
example-spring/src/main/java/io/honeycomb/Application.java
example-spring/src/main/java/io/honeycomb/HelloController.java
example-spring/src/main/resources/application.properties
pom.xml

- When using a non-classic API key... `service.name` is not properly set, resulting in traces ending up in wrong dataset. For example, with `dataset=my-dataset` and `service.name=my-service`, traces should show up in `my-service` dataset.
- set servicename in spring boot starter
- use process name instead of service name for default fallback
- don't throw on runtime exception
- use dataset for classic keys and service name for nonclassic keys
- update and add unit tests to assert ServiceName is properly used for dataset with nonclassic keys, and dataset for classic keys
- update fallback `service.name` attribute to be `unknown_service:java`.
Classic Key: set `honeycomb.beeline.dataset` and that is where data ends up in Honeycomb
NonClassic Key: set `honeycomb.beeline.service-name` and …

fix: set service name in spring boot starter
